### ISSUE TITLE
PySTEMMUS-SCOPE Output NetCDF File Generation and where to find the water stress factor?

### ISSUE THREAD

**Issue by prajzwal08** [EcoExtreML/STEMMUS_SCOPE_Processing#102]
Hi,
I'm looking for information on how pystemmusscope generates its output NetCDF file. I am looking for the code or the part of code which does it. 

Since it includes only certain variables out of many produced by STEMMUS-SCOPE, I'm interested in understanding it and how it corresponds to the original STEMMUS-SCOPE outputs in terms of units.

I couldn't locate this information in the EcoExtremeML/STEMMUS_SCOPE_Processing repository on GitHub. Could you please point me in the right direction or provide any insights on this matter?

Thank you,
Prajwal

**Comment by prajzwal08** [comment]
Following up with this,  I really wanted to check because currently in the output of STEMMUS-SCOPE, both .nc files and .mat files are generated, neither of which includes the water stress factor (sfactor) nor the leaf water potential (PSI1). Or at least, I could not find them. Could you please help me understand how I can access these variables?

**Comment by Crystal-szj** [comment]
> Following up with this, I really wanted to check because currently in the output of STEMMUS-SCOPE, both .nc files and .mat files are generated, neither of which includes the water stress factor (sfactor) nor the leaf water potential (PSI1). Or at least, I could not find them. Could you please help me understand how I can access these variables?

Hi @prajzwal08 , I pushed a new branch [`save_wsf_psiLeaf`](https://github.com/EcoExtreML/STEMMUS_SCOPE/tree/save_wsf_psiLeaf), which saves the time series water stress factor `sfactorTot` and leaf water potential `psiLeafTot` in `output.mat` for your convenience. I've tested the new branch on CRIB via [`run_model_with_different_dataset_on_CRIB.ipynb`](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/main/docs/notebooks/run_model_with_different_dataset_on_CRIB.ipynb), and it works.

Hi @bobzsu @yijianzeng, I would like to know if we should save the soil water stress factor and leaf water potential as outputs in the latest version of STEMMUS-SCOPE? If so, I'll merge the new branch into the main branch on Github. Let me know your thoughts on this matter.

**Comment by bobzsu** [comment]
sounds a good idea. Thanks.

**Comment by SarahAlidoost** [comment]
@prajzwal08 There is a function [`save`](https://docs.google.com/spreadsheets/d/1CA3aTvI9piXqRqO-3MGrsH1vW-Sd87D8iZXHGrqK42o/edit#gid=2085475627) that uses the [lookup table](https://docs.google.com/spreadsheets/d/1CA3aTvI9piXqRqO-3MGrsH1vW-Sd87D8iZXHGrqK42o/edit#gid=2085475627) to convert stemmus_scope variables from csv files to a netcdf file. See an example in cell 16 of the [notebook](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_on_different_infra/). 

@prajzwal08 and @Crystal-szj should be those two variables saved in the netcdf file too? If so, we might need to update the lookup table or the `save` function.
