### ISSUE TITLE
the EVAP variable is always zero in BMI

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE_Processing#114]
The `Èvap` variable is always zero through BMI, although it has a value. I checked that if we delete the `all_timesteps = True` in this [line](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/33adb9e19ecdedfb8446aec5a848374d416d7cfa/PyStemmusScope/bmi/variable_reference.py#L38C1-L38C28), the `Èvap` variable will get its value in BMI

**Comment by BSchilperoort** [comment]
The `all_timesteps` variable denotes if the variable is an array which contains data on all time steps. This bug probably crept in because EVAP is an array of size n_timesteps, but only the first index is used to put any value in.

**Comment by MostafaGomaa93** [comment]
> @MostafaGomaa93 Note that there are two variables `EVAP` and `Evap` 😄 . The line you mentioned is related to `EVAP` and not `Evap`. These two variables have a similar problem to variable `Trap`, see [this comment](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/271#issuecomment-2520565866). Can you also fix the code to have one variable for evapotranspiration?

Okay, I removed `EVAP` and adjusted `Evap` in this [PR](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/273)
