### ISSUE TITLE
Load MATLAB Compiler Runtime (MCR) in notebook

### ISSUE THREAD

**Issue by geek-yang** [EcoExtreML/STEMMUS_SCOPE_Processing#2]
Loading MATLAB Compiler Runtime (MCR) in the notebook will lead to an error. The current solution is to add the following codes to `run_jupyter_on_compute_node.sh` and then launch the notebook:

```bash
module load 2021
module load MCR/R2021a.3
```

To make it easier for the snellius user, it is better to find solutions to either load these modules in the notebook or provide an example `run_jupyter_on_compute_node.sh` (and explain it in the readme).

**Comment by SarahAlidoost** [comment]
To work with MCR, MATLAB Runtime path should be set for deployment. The paths are OS-dependent, see [here](https://nl.mathworks.com/help/compiler/mcr-path-settings-for-run-time-deployment.html). when using snellius, this is not a concern. 
The current solution is that on a local linux laptop we set the `LD_LIBRARY_PATH` for a linux system in the notebook or on snellius, we load modules in sbatch script. 

we need to explore docker options, for example see [this one for MCR](https://hub.docker.com/r/usuresearch/matlab-runtime/dockerfile).
