### ISSUE TITLE
STEMMUS_SCOPE executable file incompatible with Windows 

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE_Processing#27]
After installing Matlab runtime, I get the following error trying to run the executable file in Windows:

`The specified executable is not a valid application for this OS platform`

We should figure out what is required to generate an executable file that is compatible with Windows, or how to properly run the executable file on Windows.

**Comment by SarahAlidoost** [comment]
Searching in google and mathworks, it seems that cross-platform Matlab executables are not supported. The executable should be compiled on Windows. However, the license is a problem. 

One solution is to use docker. Then the windows user has to install docker. Here are some guides on installing docker on windows https://docs.docker.com/desktop/install/windows-install/ and https://www.simplilearn.com/tutorials/docker-tutorial/install-docker-on-windows. We should find out what are the minimum installation requirements to run an image (and not build an image) on windows.

**Comment by SarahAlidoost** [comment]
another solution is to use [Windows Subsystem for Linux](https://en.m.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

**Comment by SarahAlidoost** [comment]
See related issues on cross-platform Matlab executables:

- https://nl.mathworks.com/matlabcentral/answers/570208-cross-platform-os-deployment-of-compiled-applications?s_tid=answers_rc1-1_p1_Topic 
- https://nl.mathworks.com/matlabcentral/answers/282361-does-the-os-of-the-machine-i-compile-on-need-to-match-the-os-of-the-machine-i-intend-to-run-on
- https://nl.mathworks.com/matlabcentral/answers/7500-mac-matlab-installation-mcr-installer-for-linux
