### ISSUE TITLE
Matlab R2021a  incompatible with Python 3.9

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/STEMMUS_SCOPE_Processing#31]
On Snellius and CRIB, matlab `R2021a` is installed that supports python 3.7 and 3.8. see [python compatibility](https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/python-compatibility.pdf).

**Comment by BSchilperoort** [comment]
That's crazy. Python 3.7 has under a year left, and python 3.8 will reach its end of life in two years. These version checks must be hardcoded.

I'm not sure about setting the required python version to 3.8. When other users but ITC (including us...) want to use the model's executable with the python notebook / the future BMI, restricting the Python version makes no sense.

**Comment by SarahAlidoost** [comment]
agree. The conda environment with `python=3.8` is only needed to call python from matlab. The environment is needed by developers who only work with **matlab desktop interface** e.g. developers on CRIB. `PyStemmusScope` already supports both `3.8` and `3.9`.  When python 3.8 reaches its end of life, of course, matlab should be upgraded on CRIB. 

I think it is better if I create a separate environment file with `python=3.8` that will be used for this purpose. The environment does not need to be even activated outside a matlab session. We can also use the **jupyter notebook interface** on systems like snellius (call matlab from python) e.g. [run_model_in_notebook_dev.ipynb](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/main/notebooks/run_model_in_notebook_dev.ipynb).
