### ISSUE TITLE
Error using load in Matlab 

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/STEMMUS_SCOPE_Processing#38]
Related to generating `forcing_globals.mat`, matlab version `9.10.0.1684407 (R2021a) Update 3`

```
STEMMUS_SCOPE_exe(string(config_path));
    "Reading config from "    "D:\test0825\input\AR-SLu_2022-08-25-1547\AR-SLu_2022-08…"

Error using load
Unable to read MAT-file D:\test0825\input\AR-SLu_2022-08-25-1547\forcing_globals.mat. Not a binary MAT-file. Try load -ASCII
to read as text.

Error in filesread (line 24)
load(forcing_global_path, 'DELT', 'Dur_tot', 'IGBP_veg_long', 'latitude', 'longitude', 'reference_height', 'canopy_height',
'sitename')

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in STEMMUS_SCOPE (line 26)
run filesread %get paths and prepare input files

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in STEMMUS_SCOPE_exe (line 11)
run STEMMUS_SCOPE
```

**Comment by SarahAlidoost** [comment]
The MAT-file `D:\test0825\input\AR-SLu_2022-08-25-1547\forcing_globals.mat` is generated using **calling python from matlab** on a **windows** system where the system **language** is not English. Looking at the content of this file, the time is not written correctly. Hence, matlab complains about the content of the file.

To generate the MAT-file, we uses [hdf5storage.savemat](https://pythonhosted.org/hdf5storage/_modules/hdf5storage.html#savemat) that uses a [writes](https://pythonhosted.org/hdf5storage/_modules/hdf5storage.html#writes) function including `datetime.datetime.now().strftime('%a %b %d %H:%M:%S %Y')`.

Perhaps this issue will be fixed if the `forcing_globals` is saved as a netcdf file, see issue #16

**Comment by BSchilperoort** [comment]
A workaround could be to set the locale to en_US, using Python's `locale` module.
