### ISSUE TITLE
The failed actions Build for 3.8, windows-latest xarray dependencies

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/STEMMUS_SCOPE_Processing#43]
The failed actions [Build for (3.8, windows-latest](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/actions/runs/3313180997/jobs/5470809285)), [Build for (3.9, windows-latest) ](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/actions/runs/3313180997/jobs/5470809432) might be related to [this issue](https://github.com/pydata/xarray/issues/7136) in xarray.

**Comment by SarahAlidoost** [comment]
@geek-yang and @BSchilperoort  what do you think? could one of you please help to test xarray and netcdf4 installation on windows?

**Comment by BSchilperoort** [comment]
I encountered this issue recently here: https://github.com/dtscalibration/python-dts-calibration/issues/149
It actually also happened on Ubuntu and MacOS there.

We can set the `netCDF4<=1.5.8` in the config to avoid this problem for now.

Here it runs fine with netCDF `1.5.8` and xarray `2022.09.0`
