### ISSUE TITLE
PyStemmusScope_Octave Runing return an error

### ISSUE THREAD

**Issue by yijianzeng** [EcoExtreML/STEMMUS_SCOPE_Processing#72]
@SarahAlidoost @BSchilperoort When i used PyStemmusScope on Crib to run the Octave version (since the Matlab Runtime is not yet ready on Crib), i encountered the following error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [6], line 3
      1 # setup the model
      2 # here you can change the location and start & end time
----> 3 config_path = model.setup(
      4     Location="ZA-Kru",
      5     StartTime="2001-01-01T00:00",
      6     EndTime="2001-01-02T01:30",
      7 )
      9 # new config file genertaed to run the model 
     10 print(f"New config file {config_path}")

TypeError: setup() got an unexpected keyword argument 'Location'
```

**Comment by SarahAlidoost** [comment]
It seems you are not using the latest version of PyStemmusScope. Please install the latest i.e. version 0.2.0, see https://pypi.org/project/PyStemmusScope/0.2.0/ . Also, see the release note of stemmus_scope https://github.com/EcoExtreML/STEMMUS_SCOPE/releases

**Comment by yijianzeng** [comment]
> It seems you are not using the latest version of PyStemmusScope. Please install the latest i.e. version 0.2.0, see https://pypi.org/project/PyStemmusScope/0.2.0/ . Also, see the release note of stemmus_scope https://github.com/EcoExtreML/STEMMUS_SCOPE/releases

Hi Sarah, i am not sure if this is an idea to put an comment or error/reminding message that suggest users always to update it to the latest version?
