### ISSUE TITLE
The netCDF files can't be read by modelevaluation website.

### ISSUE THREAD

**Issue by Yunfei-Wang1993** [EcoExtreML/STEMMUS_SCOPE_Processing#74]
@BSchilperoort  Hi, Bart, I noticed the netCDF files generated by the latest version of pystemmusscope can't be read by modelevaluation website. I compared the new .nc files with the old ones and found that there are some differences, such as the unit of 'time' variable. Could you help to make some changes to the code?

**Comment by BSchilperoort** [comment]
Hi Yunfei, could you upload and send the old & the new netCDF files to me?

Does the ModelEvaluation website give you a clear error, if so, could you paste that here? Thanks.

**Comment by Yunfei-Wang1993** [comment]
<https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com.cn%2FB%2FAUoHuVVXm3D1jpBkEMzAvIt-RtPgAUdOnZMLA2gqWqk3c7N6YiwvXDzV%2F%24%7Bf%7D%3Fo%3DAkjX8l2HKrMMpYnSZ3Ow5SXH5u5SH52hH4qkCPg0_Ch5%26v%3D1%26x%3D3%26a%3DCAogEqtt32ExrpcuGkRVRy49nwIf9niOss3lCdSU_T7ydI0SehCsj72m8DAYrJ-4-vkwIgEAKgkC6AMA_2MShrNSBH5G0-BaBC9cPNVqJxAveEYYgWyBldmJgxJH4ozzAPJPqSmYuPcBB0zAe3VpbCAJl_Ou43Inq9Azrqh8ocHD4_X3cS3NkhB4zwh9G_SgX2fps-_c9af_RmnH7RaL%26e%3D1682004905%26fl%3D%26r%3DCCD00C5E-7E43-4867-AC90-525C3A089791-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D88928021-A625-4893-AA97-5B58997E3F59%26p%3D209%26s%3Da70dWajiGRKaF5Os8YhzwFsMUkU&uk=D-90aS_iwSS29a-ACoIlUg&f=Images.zip&sz=356395>
下载最高分辨率图像
2023年4月20日过期
Hi, Bart, the website reported the variables do not appear to exist in the .nc files. Please find the attached .nc files and reports. The 'CA-NS1_2023-03-21-0917_STEMMUS_SCOPE.nc' is the new file and 'CA-NS1_2022-07-08-1312_STEMMUS_SCOPE.nc’ is the old file.

Best, Yunfei
点按以下载<https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com.cn%2FB%2FAQznvf9aO3shM1Dv7XL1SHOleuVTAVNlBGP3pQgZJwivUg7mHgjDQ4A2%2F%24%7Bf%7D%3Fo%3DAuYOCCWrWb222Pk6K2feRU4bMzmY2D3qW-LGq5-Is-Km%26v%3D1%26x%3D3%26a%3DCAogpMFOV7SFZnhllA9lB_b7bkHHVQIDfCQ6v2oLiZxoTpASehDci72m8DAY3Ju4-vkwIgEAKgkC6AMA_wNypMVSBKV65VNaBMNDgDZqJ6Iayh-cdTIk76en3kJ-CwsypnpEDJwY9UJQ79-Lj2UN_30EL-cXT3Injlvn3LqkhzNT8pfoRAYrLzWySdE3fn05wqN_fe4cwvWtpK1Mdhs6%26e%3D1682004905%26fl%3D%26r%3D8860DF41-4547-4835-B548-51C99963D6C6-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D88928021-A625-4893-AA97-5B58997E3F59%26p%3D209%26s%3DGiu_oPMkMG-uwhkct2HD_f7UHM8&uk=8y8A66mGe2Rdc4eT8L2aBQ&f=CA-NS1_2022-07-08-1312_STEMMUS_SCOPE.nc&sz=9399164>
CA-NS1_2022-07-08-1312_STEMMUS_SCOPE.nc
9.4 MB
点按以下载<https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com.cn%2FB%2FAfOQQgaPmiemQ4H-OeFPSdQNWfD1Ac9LgsuE4T-iQIiBMgCtC7X2b5Xu%2F%24%7Bf%7D%3Fo%3DAnG_D-jmbNqsaxrS5HdomEqQWGP_pDAncaBLFtD6kVhL%26v%3D1%26x%3D3%26a%3DCAogAiKpFhV4dXzae_VZBW_ozJslZlaDfVFA3Ra_WGrqa9USehDuir2m8DAY7pq4-vkwIgEAKgkC6AMA_ygZuzxSBA1Z8PVaBPZvle5qJ_oUqeNmIaaWIn2fCrX-Ygs5GVFuBoymahTtDGa5WAt-0n3mYqUYhnInT-S_rINaTy8j0-kBGM4EtezAsu8atwKI0b90M_NQ-72TD8VUapFb%26e%3D1682004905%26fl%3D%26r%3D8237667B-7359-4B7C-AA9E-7B387D4C8704-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D88928021-A625-4893-AA97-5B58997E3F59%26p%3D209%26s%3DsHBC_HB1rPvON2Vi1QimVkrGViM&uk=UpszbK2cZb2p4bNxhW8qRg&f=CA-NS1_2023-03-21-0917_STEMMUS_SCOPE.nc&sz=16926580>
CA-NS1_2023-03-21-0917_STEMMUS_SCOPE.nc
16.9 MB
[cid:807B0BA0-5118-43F0-BE77-30FB9053B0B2]

2023年3月21日 下午11:05，Bart Schilperoort ***@***.******@***.***>> 写道：



Hi Yunfei, could you upload and send the old & the new netCDF files to me?

Does the ModelEvaluation website give you a clear error, if so, could you paste that here? Thanks.

**Comment by SarahAlidoost** [comment]
The time `units` and `calendar` are different too as `ncdump -h` shows below.  Also, there are differences between double and float. Regarding time, I guess the `datetime.strptime` caused this. if so, this [issue](https://github.com/eWaterCycle/ewatercycle/issues/90) might be useful. More investigations are needed and perhaps a test.

**old netcdf file**
``` 
ncdump -h CA-NS1_2022-07-08-1312_STEMMUS_SCOPE.nc
netcdf CA-NS1_2022-07-08-1312_STEMMUS_SCOPE {
dimensions:
        x = 1 ;
        y = 1 ;
        z = 54 ;
        time = UNLIMITED ; // (17520 currently)
        nchar = 200 ;
variables:
        double x(x) ;
        double y(y) ;
        double z(z) ;
                z:units = "depth in cm" ;
        double time(time) ;
                time:units = "seconds since 2003-01-01 00:00:00" ;
                time:calendar = "standard" ;
```

**New netcdf file**
```
ncdump -h CA-NS1_2023-03-21-0917_STEMMUS_SCOPE.nc 
netcdf CA-NS1_2023-03-21-0917_STEMMUS_SCOPE {
dimensions:
        time = 17520 ;
        y = 1 ;
        x = 1 ;
        z = 54 ;
variables:
        int64 time(time) ;
                time:units = "minutes since 2003-01-01 00:00:00" ;
                time:calendar = "proleptic_gregorian" ;
```

**Comment by yijianzeng** [comment]
Perhaps the most convenient solution now is to reset the new netcdf format to be aligned with the old one, which is the ALMA format, and digested by the modelevaluation.org.

**Comment by SarahAlidoost** [comment]
@Yunfei-Wang1993 I changed the time units and calendar of the netcdf file in [this pull request ](#76 ). Can you check if it works? You need to uninstall the current `pystemmusscope` and install it from branch `fix_issue_74`. To do so, run:
```
pip uninstall pystemmusscope
pip install git+https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git@fix_issue_74
```

**Comment by SarahAlidoost** [comment]
> As far as I can see, the only difference seems to be that the main dimensions show in a different order (however, not in a different order for the variables) and that instead of lat/lon, the new version has x/y as variables.

Some of the netcdf attrs are not shown by xarray. For example, I used `decode_times=False` in `xarray.open_dataset` to check the calendar and units of time.

**Comment by Yunfei-Wang1993** [comment]
> 

Thanks a lot, Sarah, for fixing the issue. I have regenerated the netCDF file with the new version of PyStemmusScope and it can be read by modelevaluation website.
