### ISSUE TITLE
Problems with running Model with different datasets in Linux668

### ISSUE THREAD

**Issue by prajzwal08** [EcoExtreML/STEMMUS_SCOPE_Processing#98]
Hi,
I've encountered an issue while running the STEMMUS_SCOPE model for a new test site, FR-Lgt, as part of my research project.

<img width="452" alt="image" src="https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/assets/125794225/efbe8727-d54b-46e9-a4bb-91077ea6e611">

To provide some context, I have been working on running the model for various flux net sites across Europe. I have prepared the necessary input data in the format required by pystemmusscope and have organized it within the directories ~/input/Plumber2_data/*.nc for the flux data and ~/input/Initial_condition for the initial conditions. I have ensured that the data format aligns with the model's requirements to the best of my knowledge. Additionally, I have adjusted the config_file.txt and the code according to the instructions provided in the STEMMUS_SCOPE documentation, specifically referring to the guide available at https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/main/docs/notebooks/run_model_with_different_dataset.ipynb.

However, despite successfully running the model for NL-Hor, an existing site listed in PLUMBER2, I have encountered difficulties when attempting to run it for the new test site, FR-Lgt. Although the model successfully creates the input and output directories for FR-Lgt, it encounters an error during the actual model run. Upon comparing the FR-Lgt_2024-02-19-1519_config.txt generated for the FR-Lgt instance with the configuration file created for NL-Hor, I noticed no significant differences apart from the site name and date.
So, could you please help me fix this issues?
Thanks
Prajwal

**Comment by BSchilperoort** [comment]
The error is occuring inside Matlab. Can you run that command in your terminal? The part after `Command '['` until `']' returned...`
That way you can see the Matlab error which can help find out what's going wrong.

**Comment by prajzwal08** [comment]
It says no such file or directory, while it is still there. Let me know, if i did it correctly or not. 
<img width="1275" alt="Screenshot 2024-02-19 at 07 16 21" src="https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/assets/125794225/d031948d-1895-4ab6-87c5-6d7f497b7a38">

**Comment by BSchilperoort** [comment]
> It says no such file or directory, while it is still there. Let me know, if i did it correctly or not. <img alt="Screenshot 2024-02-19 at 07 16 21" width="1275" src="https://private-user-images.githubusercontent.com/125794225/306001667-d031948d-1895-4ab6-87c5-6d7f497b7a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTYyMDUsIm5iZiI6MTcwODM1NTkwNSwicGF0aCI6Ii8xMjU3OTQyMjUvMzA2MDAxNjY3LWQwMzE5NDhkLTE4OTUtNGFiNi04N2M1LTZkN2Y0OTdiN2EzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNTE4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWIyZTZiMjk2M2FmMzk4M2U5NTcxMDNmMGMzNmEzODg5NTI1MzM1Y2U1YTEwZDNkNzFmMTY3ZjcxYTRiMzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ONd0zzN6L9jM2FUkVpYZSdtg3WO-WlJq4zFsy15E-cY">

Try it without the `'` at the start and end

**Comment by prajzwal08** [comment]
Oh sorry, Thanks . Please check this. 
<img width="1275" alt="Screenshot 2024-02-19 at 07 20 52" src="https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/assets/125794225/f2b24d56-7ffb-4645-96ba-6040b48740d8">

**Comment by BSchilperoort** [comment]
Hm. You might have to run the commands to add the Matlab runtime components to your environment...

https://nl.mathworks.com/help/compiler/mcr-path-settings-for-run-time-deployment.html

**Comment by prajzwal08** [comment]
Hi, 
I will look at this. What i got confused is it works when i change the site to NL-Hor and date while does not work for my new site. So, it Matlab runtime component was missing, it should not be running for NL-Hor too, right? Or, am i getting it wrong?
<img width="1263" alt="Screenshot 2024-02-19 at 07 26 53" src="https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/assets/125794225/e5a554e5-a913-4bd4-a531-e1461ff3631f">
Thanks

**Comment by BSchilperoort** [comment]
> Hi, I will look at this. What i got confused is it works when i change the site to NL-Hor and date while does not work for my new site. So, if Matlab runtime component was missing, it should not be running for NL-Hor too, right? Or, am i getting it wrong? <img alt="Screenshot 2024-02-19 at 07 26 53" width="1263" src="https://private-user-images.githubusercontent.com/125794225/306005029-e5a554e5-a913-4bd4-a531-e1461ff3631f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTY4ODQsIm5iZiI6MTcwODM1NjU4NCwicGF0aCI6Ii8xMjU3OTQyMjUvMzA2MDA1MDI5LWU1YTU1NGU1LWE5MTMtNGJkNC1hNTMxLWUxNDYxZmYzNjMxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNTI5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODYwMTc1YWE0YjJiMGNmOTAyOTdmNzhlZGQyZDQxMzk5OTcxMTFiNmU4ZmM2NDdhZTlkMTJlYTYxNGVmYTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N9CsuBR8inQIkrsqo2HZs_yDuwpt7kFBd2BIzfNBeNA"> Thanks

Yes but there you are not running the command in the terminal. You run matlab via the python file, which is adding the components to the PATH.

**Comment by prajzwal08** [comment]
Hi, 
Thanks! got it!
Seems like error in the data type. I will recheck my data format again and get back to you!
<img width="1230" alt="Screenshot 2024-02-19 at 07 47 19" src="https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/assets/125794225/4513c3f8-60ab-4b1d-af1f-9824cf47ea68">
